development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:834fe2401b3edb9314cbd94f423d0d4a@tetra.redistogo.com:9322/
  channel_prefix: mafia-api_production
